name: 2 - Alternative Reports Generator

on:
  #push:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      container:
        image: docker://guillaumefalourd/ritchiecli:py-3.8
      steps:
        - name: Install Github
          run: |
            apt-get install -y git
            git clone https://github.com/$GITHUB_REPOSITORY

        - name: Create report file
          env:
            USERNAME_CREDENTIAL: ${{ secrets.USERNAME_CREDENTIAL }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          run: |
            cd repositories-reports/reports
            sudo rit add repo --provider="Github" --name="formulas-github" --repoUrl="https://github.com/GuillaumeFalourd/formulas-github" --priority=1
            sudo rit set credential --provider=github --fields=username,token --values="$USERNAME_CREDENTIAL","$ACCESS_TOKEN"
            sudo rit github get insights --rit_repos="ALL"

        - name: Commit and Push new report
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          run: |
            cd repositories-reports
            git config user.name github-actions
            git config user.email github-actions@github.com
            git remote set-url origin https://x-access-token:$ACCESS_TOKEN@github.com/${{ github.repository }}
            git add .
            git commit -m "add new report"
            git push
